services:
  - type: web
    name: gitpen-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: "5001"
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
